ase_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from simulator.forms import LoginForm
import oauth2_provider.views as oauth2_views
from django.conf import settings
from simulator.views import ApiEndpoint

urlpatterns = [
    url(r'^', include('simulator.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^login$', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm}, name="login"),
    url(r'^logout$', views.logout, {'next_page': '/login'}),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^api/hello', ApiEndpoint.as_view()), 
]

# OAuth2 provider endpoints
oauth2_endpoint_views = [
    url(r'^authorize/$', oauth2_views.AuthorizationView.as_view(), name="authorize"),
    url(r'^token/$', oauth2_views.TokenView.as_view(), name="token"),
    url(r'^revoke-token/$', oauth2_views.RevokeTokenView.as_view(), name="revoke-token"),
]

if settings.DEBUG:
    # OAuth2 Application Management endpoints
    oauth2_endpoint_views += [
        url(r'^applications/$', oauth2_views.ApplicationList.as_view(), name="list"),
        url(r'^applications/register/$', oauth2_views.ApplicationRegistration.as_view(), name="register"),
        url(r'^applications/(?P<pk>\d+)/$', oauth2_views.ApplicationDetail.as_view(), name="detail"),
        url(r'^applications/(?P<pk>\d+)/delete/$', oauth2_views.ApplicationDelete.as_view(), name="delete"),
        url(r'^applications/(?P<pk>\d+)/update/$', oauth2_views.ApplicationUpdate.as_view(), name="update"),
    ]

    # OAuth2 Token Management endpoints
    oauth2_endpoint_views += [
        url(r'^authorized-tokens/$', oauth2_views.AuthorizedTokensListView.as_view(), name="authorized-token-list"),
        url(r'^authorized-tokens/(?P<pk>\d+)/delete/$', oauth2_views.AuthorizedTokenDeleteView.as_view(),
            name="authorized-token-delete"),
    ]

simulator/urls.py
from django.conf.urls import url

from . import views

app_name = "simulator"

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^login/$', views.login_req, name='login'),
    url(r'^loggedin/$', views.loggedin, name='loggedin'),
    url(r'^logout/$', views.logout_req, name='logout'),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^signedup/', views.signedup, name='signedup'),
    url(r'^profile/', views.profile, name='profile'),
    url(r'^getstockdata_views/', views.getstockdata_views,
        name='getstockdata_views'),
    url(r'^market_execution/', views.market_execution,
        name="market_execution"),
    url(r'leaderboard/', views.leaderboard,
        name="leaderboard"),
    url(r'^secret/$', views.secret_page, name='secret'),
]

simulator/models.py
from __future__ import unicode_literals

from decimal import Decimal
from django.db import models, transaction
from django.contrib.auth.models import User


class Instrument(models.Model):
    symbol = models.CharField(max_length=10)
    current_price = models.DecimalField(decimal_places=3, max_digits=10)
    last_time_updated = models.DateTimeField()

    @transaction.atomic
    def update_price(self, retrieved_price):
        self.current_price = Decimal(retrieved_price)
        print "New price: " + str(self.current_price)
        self.save()

    def __unicode__(self):
        return "Symbol: {} | Current Price: {}".format(
            self.symbol,
            self.current_price,
        )


class Position(models.Model):
    user = models.ForeignKey(User, related_name="user")
    instrument = models.ForeignKey(
        Instrument, on_delete=models.CASCADE, related_name="instrument")
    symbol = models.CharField(max_length=10)
    quantity_purchased = models.PositiveIntegerField()
    price_purchased = models.DecimalField(decimal_places=3, max_digits=10)
    date_purchased = models.DateTimeField()

    @transaction.atomic
    def market_buy(self, quantity):
        if Decimal(quantity) >= 500:
            return False
        self.quantity_purchased += Decimal(quantity)
        self.save()
        return True

    @transaction.atomic
    def market_sell(self, quantity):
        if Decimal(quantity) > self.quantity_purchased:
            return False
        else:
            self.quantity_purchased -= Decimal(quantity)
            self.save()
            return True

    @property
    def net_profit(self):
        return self.quantity_purchased * (
            self.instrument.current_price - self.price_purchased)

    def __unicode__(self):
        return ("Symbol: {} | User: {} | Quantity: {}"
                " | Price Purchased: {} | Current Price: {}".
                format(self.symbol, self.user, self.quantity_purchased,
                       self.price_purchased, self.instrument.current_price, )
               )

simulator/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm


# If you don't do this you cannot use Bootstrap CSS
class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", max_length=30, 
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))
    password = forms.CharField(label="Password", max_length=30, 
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'password'}))


class UserForm(ModelForm):
	username = forms.CharField(label="Username", max_length=30, widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))
	email = forms.CharField(label="Email", max_length=30, widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'email'}))
	password = forms.CharField(label="Password", max_length=30, widget=forms.PasswordInput())
	
	class Meta:
		model = User
		fields = ('username', 'email', 'password')

simulator/views.py
import datetime
import json
import os
import time
import glob
import matplotlib
matplotlib.use('Agg')

from decimal import Decimal
from googlefinance import getQuotes
from matplotlib import pyplot as plt
from pandas_datareader import data as web

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect

from simulator.forms import UserForm
from simulator.models import Instrument, Position


def home(request):
    if not request.user.is_authenticated:
        return render(request, 'login.html', status=403)
    else:
        return render(request, 'home.html')


def getstockdata_views(request):
    query_str = str(request.GET['query'])
    mydict = [getQuotes(query_str)[0]]
    if not mydict:
        HttpResponseRedirect(reverse('simulator:home'))
    lookuptimestamp = time.time()
    mydict[0]['LookupTimestamp'] = str(lookuptimestamp)
    p = json.dumps(mydict)
    plt.rcParams['axes.facecolor'] = '#99ff99'
    end = datetime.datetime.now()
    start = datetime.datetime(end.year - 1, end.month, end.day)
    df = web.DataReader(query_str, "yahoo", start, end)
    df[['Close']].plot(
        subplots=True, figsize=(10, 10), color='#3333ff', linewidth=1.5)
    plt.grid()
    plt.title(query_str)
    filename = \
        "simulator/static/" + "stock-graph" + str(lookuptimestamp) + ".png"
    plt.savefig(filename)
    return HttpResponse(p, content_type="application/json")


def delete_image(request):
    for f in glob.glob("simulator/static/stock-graph*"):
        os.remove(f)
    p = []  # just passing random values to check reception
    return HttpResponse(p, content_type="application/json")


def loggedin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect("/")
        else:
            return HttpResponseRedirect(reverse('simulator:login'))


def market_execution(request):
    message = ""
    success = True
    if not request.user.is_authenticated:
        return render(request, 'login.html', status=403)
    else:
        if request.method == 'POST':
            return render(request, 'home.html', status=400)
        user = request.user
        symbol = request.GET.get('symbol')
        quantity = request.GET.get('quantity')
        execution = request.GET.get('execution')
        last_trade_price = request.GET.get('price')
        ins_set = Instrument.objects.filter(symbol=symbol)
        if ins_set.count() == 0:
            ins = Instrument.objects.create(
                symbol=symbol,
                current_price=last_trade_price,
                last_time_updated=datetime.datetime.now(),
            )
        else:
            ins = Instrument.objects.get(symbol=symbol)
        pos_list = Position.objects.filter(user=user, instrument=ins)
        if pos_list.count() == 0:
            print "Pos count is 0."
            if execution == "buy":
                if Decimal(quantity) > 500:
                    success = False
                    message = "Please buy less than 500 stocks at a time."
                else:
                    Position.objects.create(
                        user=user,
                        instrument=ins,
                        symbol=symbol,
                        price_purchased=last_trade_price,
                        quantity_purchased=quantity,
                        date_purchased=datetime.datetime.now(),
                    )
                    message = "You have placed a new market buy"
            else:
                print "Reached where I want to be."
                # Selling a stock you don't own.
                message = "You cannot sell a stock you do not own."
                success = False
        else:
            pos = Position.objects.get(user=user, instrument=ins)
            if execution == "buy":
                if pos.market_buy(quantity):
                    message = "You have placed a market buy."
                else:
                    message = "Your market buy wasn't processed. " \
                              "Please buy less than 500 stocks at a time."
                    success = False
            if execution == "sell":
                if pos.market_sell(quantity):
                    if pos.quantity_purchased == 0:
                        pos.delete()
                    message = "You have placed a market sell."
                else:
                    message = 'Please do not attempt to sell more ' \
                              'than you currently own of this stock.'
                    success = False
        status_code = 200 if success else 400
        response = {
            "status": 200,
            "message": message
        }
        return HttpResponse(
            json.dumps(response),
            content_type="application/json",
            status=status_code)


def login_req(request):
    return render(request, 'login.html')


def logout_req(request):
    logout(request)
    return HttpResponseRedirect("/login")


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(**form.cleaned_data)
            user.save()
            login(request, user)
            return HttpResponseRedirect("/")
    else:
        form = UserForm()
    return render(request, 'signup.html', {'form': form})


def signedup(request):
    return render(request, 'signedup.html')


def profile(request):
    if not request.user.is_authenticated:
        return render(request, 'login.html', status=403)
    else:
        user = request.user
        context = {"user": user}
        positions = Position.objects.filter(user=request.user)
        portfolio_value = 0
        for position in positions:
            portfolio_value = portfolio_value + \
                              (position.instrument.current_price *
                               position.quantity_purchased)
        context["portfolio_value"] = portfolio_value
        context["positions"] = positions
        return render(request, 'profile.html', context=context)


def leaderboard(request):
    if not request.user.is_authenticated:
        return render(request, 'login.html', status=403)
    else:
        users = User.objects.all()
        user_list = []
        context = {}
        for user in users:
            portfolio_value, net_plus_minus = \
                _update_and_return_user_portfolio_value(user)
            user_struct = {
                "user": user,
                "portfolio_value": portfolio_value,
                "net_plus_minus": net_plus_minus,
            }
            user_list.append(user_struct)
        user_list = sorted(user_list,
                           key=lambda k: k['net_plus_minus'], reverse=True)
        context["users"] = user_list
        return render(request, 'leaderboard.html', context=context)


def _update_and_return_user_portfolio_value(user):
    positions = Position.objects.filter(user=user)
    portfolio_value = 0
    net_plus_minus = 0
    for position in positions:
        i = position.instrument
        portfolio_value = portfolio_value + \
                          (i.current_price * position.quantity_purchased)
        net_plus_minus = \
            net_plus_minus + \
            (i.current_price - position.price_purchased) \
            * position.quantity_purchased
    return portfolio_value, net_plus_minus

simulator/templates/base.html
<head>
{% load static %}
   <link rel="stylesheet" type="text/css" media="all" href="{% static 'css/style.css' %}">
</head>
<body>
    {% block navbar %}
    <div class="nav">
        <p class="name">WatchDog</p>
        <ul>
            <li><a href="{% url 'simulator:home' %}"><img src="/static/pictures/home.jpg" alt="Home" style="width:20px;height:20px;"></a></li>
            <li><a href="{% url 'simulator:profile' %}"><img src="/static/pictures/profile.jpg" alt="Profile" style="width:20px;height:20px;"></a></li>
            <li><a href="{% url 'simulator:leaderboard' %}"><img src="/static/pictures/leaderboard.jpg" alt="Leaderboard" style="width:20px;height:20px;"></a></li>
            <li class="subNav">
                <a href="#" class="dropbtn">{{ request.user.get_username }} <span class="arrow">&#9660;</span></a>
                <div class="dropdown-content">
                  <a href="{% url 'simulator:logout' %}" method="post">
                    {% csrf_token %}
                    <!-- <button class="logout">Logout</button> -->
                    <class="logout">Logout</button>
                  </a>
                </div>
            </li>
            <!-- <li class="dropdown">
              <a href="javascript:void(0)" class="dropbtn">Dropdown</a>
              <div class="dropdown-content">
                <a href="#">Link 1</a>
                <a href="#">Link 2</a>
                <a href="#">Link 3</a>
              </div>
            </li> -->
        </ul>
        <!-- <p class="uppercase">Welcome {{ request.user.get_username }}</p> -->
    </div>
    {% endblock %}

    {% block content %}{% endblock %}
</body>

simulator/templates/home.html
{% extends 'base.html' %}

{% block content %}

  {% load static %}
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
  <title>Stock WatchDog</title>
  <link rel="stylesheet" type="text/css" media="all" href="{% static 'css/style.css' %}">
  <script type="text/javascript" src="{% static 'js/jquery-1.9.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery.autocomplete.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/stock_company-autocomplete.js' %}"></script>
</head>

<body>
<!-- Hacky fix for searching without stock name issue -->
<div id="hiddendiv" style="display:none">not_autocomplete</div>
              <!-- The Modal -->

<div id="myModal" class="modal">

  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">×</span>

    <div class="toleft">
      <div class="sameline"><pre><p>Stock Name:                        </p></pre></div>
      <div class="sameline"><input type="button" class="modalinfobuttons" value="Input Button" id = "hit1"></div><br><br>
      <div class="sameline"><pre><p>Stock Symbol:                      </p></pre></div>
      <div class="sameline"><input type="button" class="modalinfobuttons" value="Input Button" id = "hit2"></div><br><br>
      <div class="sameline"><pre><p>Stock Market:                       </p></pre></div>
      <div class="sameline"><input type="button" class="modalinfobuttons" value="Input Button" id = "hit3"></div><br><br>
      <div class="sameline"><pre><p>Stock Price:                           </p></pre></div>
      <div class="sameline"><input type="button" class="modalinfobuttons" value="Input Button" id = "hit4"></div><br><br>
      <div class="sameline"><pre><p>Last Trade Date and Time: </p></pre></div>
      <div class="sameline"><input type="button" class="modalinfobuttons" value="Input Button" id = "hit5"></div><br><br>
    </div>

    <div class="toright">
      <img src = "../static/loading-dog.gif" data-original = "../static/foo567.jpg" alt="Dog" class= "dog_gif" id = "stockgraph">

      <div class="purchase">
        <p>Quantity:</p>
        <input type="number" id ="quant" name="quantity" min="1" value="1">
        <br>
        <p>Buy:</p>
        <input type="radio" id="radio1" name="market" value="buy" checked="checked">
        <br>
        <p>Sell:</p>
        <input type="radio" id="radio2" name="market" value="sell">
        <br>
        <button class="button" type="submit" id="marketExecution" style="float:righ;t">Go</button>
      </div>

    </div>
  </div>
</div>
<div id="outerMarketStatus">
    <!-- if a trade has been placed, the data message goes here -->
</div>
  <p id="demo"></p>
  <div id="w">
    <div id="content">
      <h1>Stock Market Company Lookup</h1>
      <div id="searchfield">
        <form method="post"><input type="text" name="company" class="biginput" id="autocomplete" method="POST" placeholder="Search a company">
         <a href="#" class="button" id="hit">Search</a>

<script>
// Get the modal
var modal = document.getElementById('myModal');

// Get the button that opens the modal
var btn = document.getElementById("hit");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks the button, open the modal
btn.onclick = function() {
	//As matplotlib takes arounds 1-2 secs for creating the image, we wait for 3 secs before finally loading it.
if(document.getElementById("hiddendiv").innerHTML=="autocomplete"){
      setTimeout(function () {

		//We use different classes for stockgraph and dog gif which helps differentiate their css content.
		var aa = document.getElementById("stockgraph").getAttribute("data-original");
		document.getElementById("stockgraph").setAttribute("src", aa);
		//This timeout is to make sure that only after the image is set to graph will its size increase. Or else earlier
		//the dog gif was increasing to the size of our graph.
		setTimeout(function () {
			document.getElementById("stockgraph").className="stock_graph";
		    }, 10);


		    }, 3000);

     modal.style.display = "block";
}
}






// When the user clicks on <span> (x), close the modal
span.onclick = function() {
//We need to change the image back to dog gif for the next time the user searches for a stock
    document.getElementById("stockgraph").className="dog_gif";
    document.getElementById("hiddendiv").innerHTML="not_autocomplete";
    document.getElementById("quant").value = 1;
    $("#stockgraph").attr("src","../static/loading-dog.gif");
    $('#autocomplete').val("");
    modal.style.display = "none";

   $.getJSON("delete_image").done(function(data){});
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {

    if (event.target == modal) {
        document.getElementById("stockgraph").className="dog_gif";
        document.getElementById("hiddendiv").innerHTML="not_autocomplete";
        document.getElementById("quant").value = 1;
	$("#stockgraph").attr("src","../static/loading-dog.gif");
        modal.style.display = "none";
    $('#autocomplete').val("");
	$.getJSON("delete_image").done(function(data){});
    }
}
</script>
        </form>
      </div><!-- @end #searchfield -->
    </div><!-- @end #content -->
  </div><!-- @end #w -->
</body>


{% endblock%}

simulator/templates/leaderboard.html
{% extends 'base.html' %}

{% block page_name %}Stock Leaderboard{% endblock %}

{% block content %}
<div class="leaderboardContainer">
    <table class="leaderboardTable" style="align: center; border: 1px solid #CCFFCC;">
        <tr>
            <th>Ranking</th>
            <th>User</th>
            <th>Portfolio Value</th>
            <th>Net +/-</th>
        </tr>
        {% if users %}
            {% for user in users %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ user.user.username }}</td>
                    <td>{{ user.portfolio_value }}</td>
                    <td>{{ user.net_plus_minus }}</td>
                </tr>
            {% endfor %}
        {% endif %}
    </table>
</div>
{% endblock %}

simulator/templates/login.html
{% extends 'login_base.html' %}

{% block content %}
    {% if form.errors %}

<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}

<p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}

<p>Please login to see this page.</p>
    {% endif %}
{% endif %}


<div class="loginForm">
    <form action="{% url 'simulator:loggedin' %}" method="post">
        {% csrf_token %}
        <p class="bs-component">
            <!-- <table>
                    <tr>
                        <td>{{ form.username.label_tag }}</td>
                        <td>{{ form.username }}</td>
                    </tr>
                    <tr>
                        <td>{{ form.password.label_tag }}</td>
                        <td>{{ form.password }}</td>
                    </tr>
            </table> -->        
            <label for='username'> Username: </label> 
            <input id='username' type='text' name='username' maxlength='100' required /> <br> 
            <label for='password'> Password: </label>
            <input id='password' type='password' name='password' maxlength='100' required /> <br>
            <input type='submit' value='Login' /> 
        </p>

        <!-- <p class="bs-component">
            <input class="btn btn-success btn-sm" type="submit" value="Login" />
        </p> -->
        <!-- <input type="hidden" name="next" value="{{ next }}" /> -->
    </form>

    <a href="/signup"><button class="submission" value="Register">Register</button></a>
    <br>
    <!--<a href="">Forgot your password?</a>-->
</div>

{% endblock %}

simulator/templates/login_base.html
<head>
    <link rel="stylesheet" type="text/css" href="../static/css/style.css">
   <link rel='shortcut icon' href='/static/favicon.ico' type='image/x-icon'/>
</head>
<body>
    {% block navbar %}
    <div class="nav">
        <span class="navMidHeader">Welcome to Watchdog!</span>
    </div>
    {% endblock %}
    <br>
    <div class="loginImage">
        <img class="dogImage" src="../static/dog_stock.jpg" alt="image not found">
    </div>
    <div class="loginInfo">
        {% block content %}{% endblock %}
    </div>
    <!-- <div>
         <a href="/logout">Logout</a>
    </div> -->

</body>

simulator/templates/modal.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <p>helo supper</p>
</head>
</html>

simulator/templates/profile.html
{% extends 'base.html' %}

{% block page_name %}User Profile{% endblock %}

{% block content %}
<div id="userBasicInfo">
    <p>Name: {{ user.username}}</p>
    <p>Portfolio Value: {{ portfolio_value }} </p>
</div>

<div id="userStockTable">
    <table style="border-spacing: 90px 0px;">
        <tr>
            <th>Stock Symbol</th> 
            <th>Quantity Purchased</th>
            <th>Price Purchased</th>
            <th>Market Price</th>
            <th>Current Net Profit</th>
        </tr>
        
        {% if positions %}
        {% for position in positions %}
        <tr> 
            <td>{{ position.symbol }}</td>
            <td>{{ position.quantity_purchased }}</td>
            <td>{{ position.price_purchased }}</td>
            <td>{{ position.instrument.current_price }}</td>
            <td>{{ position.net_profit }}</td>
        </tr>
        {% endfor %}
        {% endif %}    
    </table>
</div>

{% endblock %}

simulator/templates/signedup.html
{% extends 'login_base.html' %}

{% block content %}

<div>
    <div class="row">
        <div>
        	<a href="/logout"><button class="logout" value="Login">Logout</button></a>
            <h1>Thank You!!</h1>
            <p>
            	You will receive an email briefly with the security key.
            </p>            
        </div>
    </div>
</div>
{% endblock %}

simulator/templates/signup.html
{% extends 'login_base.html' %}

{% block content %}
    {% if form.errors %}
{% endif %}

<h1>Sign Up</h1>
{% if error_message %}
<p style="color: red;">Signup unsuccessful.</p>
{% endif %}
<div class="loginForm">
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <a href="/signedup"><input type="submit" value="Sign Up" /></a>

    </form>
</div>

{% endblock %}

simulator/templates/test.html
{% extends 'login_base.html' %}

{% block content %}

<form action="{% url 'loggedin' %}" method="post">
    {% csrf_token %}
    <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
    </table>

    <input type="submit" value="Login" />
</form>

{% endblock %}